default: &default
  adapter: postgresql
  encoding: unicode
  timeout: 5000
  url: <%= ENV['DATABASE_URL'] %>

local_db: &local
  host: 'localhost'
  username: <%= ENV.fetch('WILCO_DB_USER', 'wilco') %>
  password: <%= ENV.fetch('WILCO_DB_PASS', 'wilco') %>

development:
  <<: *default
  <<: *local
  pool: 5
  database: 'anythink'

test:
  <<: *default
  <<: *local
  database: 'anythink_test'

production:
  <<: *default
  pool: 5
  prepared_statements: false
  advisory_locks: false
